config/routes.rb
Myapp::Application.routes.draw do
  resources :card_details

  resources :shipping_details

  devise_for :admins
  resources :products

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  namespace :admins do
  	get 'dashboard' => 'home#dashboard'
  		
  end

  
end

app/models/card_detail.rb
class CardDetail < ActiveRecord::Base
	belongs_to :user
end

app/controllers/card_details_controller.rb
class CardDetailsController < ApplicationController
  before_action :set_card_detail, only: [:show, :edit, :update, :destroy]

  # GET /card_details
  # GET /card_details.json
  def index
    @card_details = CardDetail.all
  end

  # GET /card_details/1
  # GET /card_details/1.json
  def show
  end

  # GET /card_details/new
  def new
    @card_detail = CardDetail.new
  end

  # GET /card_details/1/edit
  def edit
  end

  # POST /card_details
  # POST /card_details.json
  def create
    @card_detail = CardDetail.new(card_detail_params)

    respond_to do |format|
      if @card_detail.save
        format.html { redirect_to @card_detail, notice: 'Card detail was successfully created.' }
        format.json { render action: 'show', status: :created, location: @card_detail }
      else
        format.html { render action: 'new' }
        format.json { render json: @card_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /card_details/1
  # PATCH/PUT /card_details/1.json
  def update
    respond_to do |format|
      if @card_detail.update(card_detail_params)
        format.html { redirect_to @card_detail, notice: 'Card detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /card_details/1
  # DELETE /card_details/1.json
  def destroy
    @card_detail.destroy
    respond_to do |format|
      format.html { redirect_to card_details_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card_detail
      @card_detail = CardDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_detail_params
      params.require(:card_detail).permit(:name_on_card, :card_number, :card_expiry_date, :cvv, :user_id)
    end
end

app/helpers/card_details_helper.rb
module CardDetailsHelper
end

app/views/card_details/_form.html.haml
= simple_form_for(@card_detail) do |f|
  = f.error_notification

  / .form-inputs
  /   = f.input :name_on_card
  /   = f.input :card_number
  /   = f.input :card_expiry_date
  /   = f.input :cvv
  /   = f.input :user_id

  / .form-actions
  /   = f.button :submit


.container
  .row-fluid
    %form.form-horizontal
      %fieldset
        #legend
          %legend Payment
        / Name
        .control-group
          %label.control-label{for: "username"} Card Holder's Name
          .controls
            %input#username.input-xlarge{name: "username", placeholder: "", type: "text"}/
        / Card Number
        .control-group
          %label.control-label{for: "email"} Card Number
          .controls
            %input#email.input-xlarge{name: "email", placeholder: "", type: "text"}/
        / Expiry
        .control-group
          %label.control-label{for: "password"} Card Expiry Date
          .controls
            %select#expiry_month.span3{name: "expiry_month"}
              %option
              %option{value: "01"} Jan (01)
              %option{value: "02"} Feb (02)
              %option{value: "03"} Mar (03)
              %option{value: "04"} Apr (04)
              %option{value: "05"} May (05)
              %option{value: "06"} June (06)
              %option{value: "07"} July (07)
              %option{value: "08"} Aug (08)
              %option{value: "09"} Sep (09)
              = succeed "1" do
                %option{value: "10"} Oct (10)
              %option{value: "11"} Nov (11)
              %option{value: "12"} Dec (12)
            %select.span2{name: "expiry_year"}
              %option{value: "13"} 2013
              %option{value: "14"} 2014
              %option{value: "15"} 2015
              %option{value: "16"} 2016
              %option{value: "17"} 2017
              %option{value: "18"} 2018
              %option{value: "19"} 2019
              %option{value: "20"} 2020
              %option{value: "21"} 2021
              %option{value: "22"} 2022
              %option{value: "23"} 2023
        / CVV
        .control-group
          %label.control-label{for: "password_confirm"} Card CVV
          .controls
            %input#password_confirm.span2{name: "password_confirm", placeholder: "", type: "password"}/
        / Save card
        .control-group
          .controls
            %label.checkbox{for: "save_card"}
              %input#save_card{type: "checkbox", value: "option1"}/
              Save card on file?
        / Submit
        .control-group
          .controls
            %button.btn.btn-success Pay Now

app/views/card_details/edit.html.haml
%h1 Editing card_detail

= render 'form'

= link_to 'Show', @card_detail
\|
= link_to 'Back', card_details_path

app/views/card_details/index.html.haml
%h1 Listing card_details

%table
  %tr
    %th Name on card
    %th Card number
    %th Card expiry date
    %th Cvv
    %th User
    %th
    %th
    %th

  - @card_details.each do |card_detail|
    %tr
      %td= card_detail.name_on_card
      %td= card_detail.card_number
      %td= card_detail.card_expiry_date
      %td= card_detail.cvv
      %td= card_detail.user_id
      %td= link_to 'Show', card_detail
      %td= link_to 'Edit', edit_card_detail_path(card_detail)
      %td= link_to 'Destroy', card_detail, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Card detail', new_card_detail_path

app/views/card_details/new.html.haml
%h1 Card Detail

= render 'form'

= link_to 'Back', card_details_path

app/views/card_details/show.html.haml
%p#notice= notice

%p
  %b Name on card:
  = @card_detail.name_on_card
%p
  %b Card number:
  = @card_detail.card_number
%p
  %b Card expiry date:
  = @card_detail.card_expiry_date
%p
  %b Cvv:
  = @card_detail.cvv
%p
  %b User:
  = @card_detail.user_id

= link_to 'Edit', edit_card_detail_path(@card_detail)
\|
= link_to 'Back', card_details_path