config/routes.rb
Myapp::Application.routes.draw do
  resources :card_details

  resources :shipping_details

  devise_for :admins
  resources :products

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  namespace :admins do
  	get 'dashboard' => 'home#dashboard'
  		
  end

  
end

app/models/shipping_detail.rb
class ShippingDetail < ActiveRecord::Base
	belongs_to :user
end

app/controllers/shipping_details_controller.rb
class ShippingDetailsController < ApplicationController
  before_action :set_shipping_detail, only: [:show, :edit, :update, :destroy]

  # GET /shipping_details
  # GET /shipping_details.json
  def index
    @shipping_details = ShippingDetail.all
  end

  # GET /shipping_details/1
  # GET /shipping_details/1.json
  def show
  end

  # GET /shipping_details/new
  def new
    @shipping_detail = ShippingDetail.new
  end

  # GET /shipping_details/1/edit
  def edit
  end

  # POST /shipping_details
  # POST /shipping_details.json
  def create
    @shipping_detail = ShippingDetail.new(shipping_detail_params)

    respond_to do |format|
      if @shipping_detail.save
        format.html { redirect_to @shipping_detail, notice: 'Shipping detail was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shipping_detail }
      else
        format.html { render action: 'new' }
        format.json { render json: @shipping_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shipping_details/1
  # PATCH/PUT /shipping_details/1.json
  def update
    respond_to do |format|
      if @shipping_detail.update(shipping_detail_params)
        format.html { redirect_to @shipping_detail, notice: 'Shipping detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shipping_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipping_details/1
  # DELETE /shipping_details/1.json
  def destroy
    @shipping_detail.destroy
    respond_to do |format|
      format.html { redirect_to shipping_details_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipping_detail
      @shipping_detail = ShippingDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipping_detail_params
      params.require(:shipping_detail).permit(:full_address_name, :address_line_one, :address_line_two, :city_town, :state, :zip, :country, :user_id)
    end
end

app/helpers/shipping_details_helper.rb
module ShippingDetailsHelper
end

app/views/shipping_details/_form.html.haml
= simple_form_for(@shipping_detail) do |f|
  = f.error_notification

  / .form-inputs
  /   = f.input :full_address_name
  /   = f.input :address_line_one
  /   = f.input :address_line_two
  /   = f.input :city_town
  /   = f.input :state
  /   = f.input :zip
  /   = f.input :country
  /   = f.input :user_id

  / .form-actions
  /   = f.button :submit

.container
  .row
    %form.form-horizontal
      %fieldset
        / Address form
        %h2 Shipping Address
        / full-name input
        .control-group
          %label.control-label Full Name To Address
          .controls
            %input#full-name.input-xlarge{name: "full_address_name", placeholder: "full name", type: "text"}/
            %p.help-block
        / address-line1 input
        .control-group
          %label.control-label Address Line 1
          .controls
            %input#address-line1.input-xlarge{name: "address_line_one", placeholder: "address line 1", type: "text"}/
            %p.help-block Street address, P.O. box, company name, c/o
        / address-line2 input
        .control-group
          %label.control-label Address Line 2
          .controls
            %input#address-line2.input-xlarge{name: "address_line_two", placeholder: "address line 2", type: "text"}/
            %p.help-block Apartment, suite , unit, building, floor, etc.
        / city input
        .control-group
          %label.control-label City / Town
          .controls
            %input#city.input-xlarge{name: "city_town", placeholder: "city", type: "text"}/
            %p.help-block
        / region input
        .control-group
          %label.control-label State / Province / Region
          .controls
            %input#region.input-xlarge{name: "state", placeholder: "state / province / region", type: "text"}/
            %p.help-block
        / postal-code input
        .control-group
          %label.control-label Zip / Postal Code
          .controls
            %input#postal-code.input-xlarge{name: "zip", placeholder: "zip or postal code", type: "text"}/
            %p.help-block
        / country select
        .control-group
          %label.control-label Country
          .controls
            %select#country.input-xlarge{name: "country"}
              %option{selected: "selected", value: ""} (please select a country)
              %option{value: "AF"} Afghanistan
              %option{value: "AL"} Albania
              %option{value: "DZ"} Algeria
              %option{value: "AS"} American Samoa
              %option{value: "AD"} Andorra
              %option{value: "AO"} Angola
              %option{value: "AI"} Anguilla
              %option{value: "AQ"} Antarctica
              %option{value: "AG"} Antigua and Barbuda
              %option{value: "AR"} Argentina
              %option{value: "AM"} Armenia
              %option{value: "AW"} Aruba
              %option{value: "AU"} Australia
              %option{value: "AT"} Austria
              %option{value: "AZ"} Azerbaijan
              %option{value: "BS"} Bahamas
              %option{value: "BH"} Bahrain
              %option{value: "BD"} Bangladesh
              %option{value: "BB"} Barbados
              %option{value: "BY"} Belarus
              %option{value: "BE"} Belgium
              %option{value: "BZ"} Belize
              %option{value: "BJ"} Benin
              %option{value: "BM"} Bermuda
              %option{value: "BT"} Bhutan
              %option{value: "BO"} Bolivia
              %option{value: "BA"} Bosnia and Herzegowina
              %option{value: "BW"} Botswana
              %option{value: "BV"} Bouvet Island
              %option{value: "BR"} Brazil
              %option{value: "IO"} British Indian Ocean Territory
              %option{value: "BN"} Brunei Darussalam
              %option{value: "BG"} Bulgaria
              %option{value: "BF"} Burkina Faso
              %option{value: "BI"} Burundi
              %option{value: "KH"} Cambodia
              %option{value: "CM"} Cameroon
              %option{value: "CA"} Canada
              %option{value: "CV"} Cape Verde
              %option{value: "KY"} Cayman Islands
              %option{value: "CF"} Central African Republic
              %option{value: "TD"} Chad
              %option{value: "CL"} Chile
              %option{value: "CN"} China
              %option{value: "CX"} Christmas Island
              %option{value: "CC"} Cocos (Keeling) Islands
              %option{value: "CO"} Colombia
              %option{value: "KM"} Comoros
              %option{value: "CG"} Congo
              %option{value: "CD"} Congo, the Democratic Republic of the
              %option{value: "CK"} Cook Islands
              %option{value: "CR"} Costa Rica
              %option{value: "CI"} Cote d'Ivoire
              %option{value: "HR"} Croatia (Hrvatska)
              %option{value: "CU"} Cuba
              %option{value: "CY"} Cyprus
              %option{value: "CZ"} Czech Republic
              %option{value: "DK"} Denmark
              %option{value: "DJ"} Djibouti
              %option{value: "DM"} Dominica
              %option{value: "DO"} Dominican Republic
              %option{value: "TP"} East Timor
              %option{value: "EC"} Ecuador
              %option{value: "EG"} Egypt
              %option{value: "SV"} El Salvador
              %option{value: "GQ"} Equatorial Guinea
              %option{value: "ER"} Eritrea
              %option{value: "EE"} Estonia
              %option{value: "ET"} Ethiopia
              %option{value: "FK"} Falkland Islands (Malvinas)
              %option{value: "FO"} Faroe Islands
              %option{value: "FJ"} Fiji
              %option{value: "FI"} Finland
              %option{value: "FR"} France
              %option{value: "FX"} France, Metropolitan
              %option{value: "GF"} French Guiana
              %option{value: "PF"} French Polynesia
              %option{value: "TF"} French Southern Territories
              %option{value: "GA"} Gabon
              %option{value: "GM"} Gambia
              %option{value: "GE"} Georgia
              %option{value: "DE"} Germany
              %option{value: "GH"} Ghana
              %option{value: "GI"} Gibraltar
              %option{value: "GR"} Greece
              %option{value: "GL"} Greenland
              %option{value: "GD"} Grenada
              %option{value: "GP"} Guadeloupe
              %option{value: "GU"} Guam
              %option{value: "GT"} Guatemala
              %option{value: "GN"} Guinea
              %option{value: "GW"} Guinea-Bissau
              %option{value: "GY"} Guyana
              %option{value: "HT"} Haiti
              %option{value: "HM"} Heard and Mc Donald Islands
              %option{value: "VA"} Holy See (Vatican City State)
              %option{value: "HN"} Honduras
              %option{value: "HK"} Hong Kong
              %option{value: "HU"} Hungary
              %option{value: "IS"} Iceland
              %option{value: "IN"} India
              %option{value: "ID"} Indonesia
              %option{value: "IR"} Iran (Islamic Republic of)
              %option{value: "IQ"} Iraq
              %option{value: "IE"} Ireland
              %option{value: "IL"} Israel
              %option{value: "IT"} Italy
              %option{value: "JM"} Jamaica
              %option{value: "JP"} Japan
              %option{value: "JO"} Jordan
              %option{value: "KZ"} Kazakhstan
              %option{value: "KE"} Kenya
              %option{value: "KI"} Kiribati
              %option{value: "KP"} Korea, Democratic People's Republic of
              %option{value: "KR"} Korea, Republic of
              %option{value: "KW"} Kuwait
              %option{value: "KG"} Kyrgyzstan
              %option{value: "LA"} Lao People's Democratic Republic
              %option{value: "LV"} Latvia
              %option{value: "LB"} Lebanon
              %option{value: "LS"} Lesotho
              %option{value: "LR"} Liberia
              %option{value: "LY"} Libyan Arab Jamahiriya
              %option{value: "LI"} Liechtenstein
              %option{value: "LT"} Lithuania
              %option{value: "LU"} Luxembourg
              %option{value: "MO"} Macau
              %option{value: "MK"} Macedonia, The Former Yugoslav Republic of
              %option{value: "MG"} Madagascar
              %option{value: "MW"} Malawi
              %option{value: "MY"} Malaysia
              %option{value: "MV"} Maldives
              %option{value: "ML"} Mali
              %option{value: "MT"} Malta
              %option{value: "MH"} Marshall Islands
              %option{value: "MQ"} Martinique
              %option{value: "MR"} Mauritania
              %option{value: "MU"} Mauritius
              %option{value: "YT"} Mayotte
              %option{value: "MX"} Mexico
              %option{value: "FM"} Micronesia, Federated States of
              %option{value: "MD"} Moldova, Republic of
              %option{value: "MC"} Monaco
              %option{value: "MN"} Mongolia
              %option{value: "MS"} Montserrat
              %option{value: "MA"} Morocco
              %option{value: "MZ"} Mozambique
              %option{value: "MM"} Myanmar
              %option{value: "NA"} Namibia
              %option{value: "NR"} Nauru
              %option{value: "NP"} Nepal
              %option{value: "NL"} Netherlands
              %option{value: "AN"} Netherlands Antilles
              %option{value: "NC"} New Caledonia
              %option{value: "NZ"} New Zealand
              %option{value: "NI"} Nicaragua
              %option{value: "NE"} Niger
              %option{value: "NG"} Nigeria
              %option{value: "NU"} Niue
              %option{value: "NF"} Norfolk Island
              %option{value: "MP"} Northern Mariana Islands
              %option{value: "NO"} Norway
              %option{value: "OM"} Oman
              %option{value: "PK"} Pakistan
              %option{value: "PW"} Palau
              %option{value: "PA"} Panama
              %option{value: "PG"} Papua New Guinea
              %option{value: "PY"} Paraguay
              %option{value: "PE"} Peru
              %option{value: "PH"} Philippines
              %option{value: "PN"} Pitcairn
              %option{value: "PL"} Poland
              %option{value: "PT"} Portugal
              %option{value: "PR"} Puerto Rico
              %option{value: "QA"} Qatar
              %option{value: "RE"} Reunion
              %option{value: "RO"} Romania
              %option{value: "RU"} Russian Federation
              %option{value: "RW"} Rwanda
              %option{value: "KN"} Saint Kitts and Nevis
              %option{value: "LC"} Saint LUCIA
              %option{value: "VC"} Saint Vincent and the Grenadines
              %option{value: "WS"} Samoa
              %option{value: "SM"} San Marino
              %option{value: "ST"} Sao Tome and Principe
              %option{value: "SA"} Saudi Arabia
              %option{value: "SN"} Senegal
              %option{value: "SC"} Seychelles
              %option{value: "SL"} Sierra Leone
              %option{value: "SG"} Singapore
              %option{value: "SK"} Slovakia (Slovak Republic)
              %option{value: "SI"} Slovenia
              %option{value: "SB"} Solomon Islands
              %option{value: "SO"} Somalia
              %option{value: "ZA"} South Africa
              %option{value: "GS"} South Georgia and the South Sandwich Islands
              %option{value: "ES"} Spain
              %option{value: "LK"} Sri Lanka
              %option{value: "SH"} St. Helena
              %option{value: "PM"} St. Pierre and Miquelon
              %option{value: "SD"} Sudan
              %option{value: "SR"} Suriname
              %option{value: "SJ"} Svalbard and Jan Mayen Islands
              %option{value: "SZ"} Swaziland
              %option{value: "SE"} Sweden
              %option{value: "CH"} Switzerland
              %option{value: "SY"} Syrian Arab Republic
              %option{value: "TW"} Taiwan, Province of China
              %option{value: "TJ"} Tajikistan
              %option{value: "TZ"} Tanzania, United Republic of
              %option{value: "TH"} Thailand
              %option{value: "TG"} Togo
              %option{value: "TK"} Tokelau
              %option{value: "TO"} Tonga
              %option{value: "TT"} Trinidad and Tobago
              %option{value: "TN"} Tunisia
              %option{value: "TR"} Turkey
              %option{value: "TM"} Turkmenistan
              %option{value: "TC"} Turks and Caicos Islands
              %option{value: "TV"} Tuvalu
              %option{value: "UG"} Uganda
              %option{value: "UA"} Ukraine
              %option{value: "AE"} United Arab Emirates
              %option{value: "GB"} United Kingdom
              %option{value: "US"} United States
              %option{value: "UM"} United States Minor Outlying Islands
              %option{value: "UY"} Uruguay
              %option{value: "UZ"} Uzbekistan
              %option{value: "VU"} Vanuatu
              %option{value: "VE"} Venezuela
              %option{value: "VN"} Viet Nam
              %option{value: "VG"} Virgin Islands (British)
              %option{value: "VI"} Virgin Islands (U.S.)
              %option{value: "WF"} Wallis and Futuna Islands
              %option{value: "EH"} Western Sahara
              %option{value: "YE"} Yemen
              %option{value: "YU"} Yugoslavia
              %option{value: "ZM"} Zambia
              %option{value: "ZW"} Zimbabwe

        %div
          %button.btn.btn-primary Update

app/views/shipping_details/edit.html.haml
%h1 Editing shipping_detail

= render 'form'

= link_to 'Show', @shipping_detail
\|
= link_to 'Back', shipping_details_path

app/views/shipping_details/index.html.haml
%h1 Listing shipping_details

%table
  %tr
    %th Full address name
    %th Address line one
    %th Address line two
    %th City town
    %th State
    %th Zip
    %th Country
    %th User
    %th
    %th
    %th

  - @shipping_details.each do |shipping_detail|
    %tr
      %td= shipping_detail.full_address_name
      %td= shipping_detail.address_line_one
      %td= shipping_detail.address_line_two
      %td= shipping_detail.city_town
      %td= shipping_detail.state
      %td= shipping_detail.zip
      %td= shipping_detail.country
      %td= shipping_detail.user_id
      %td= link_to 'Show', shipping_detail
      %td= link_to 'Edit', edit_shipping_detail_path(shipping_detail)
      %td= link_to 'Destroy', shipping_detail, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Shipping detail', new_shipping_detail_path

app/views/shipping_details/new.html.haml
%h1 Shipping Detail

= render 'form'

= link_to 'Back', shipping_details_path

app/views/shipping_details/show.html.haml
%p#notice= notice

%p
  %b Full address name:
  = @shipping_detail.full_address_name
%p
  %b Address line one:
  = @shipping_detail.address_line_one
%p
  %b Address line two:
  = @shipping_detail.address_line_two
%p
  %b City town:
  = @shipping_detail.city_town
%p
  %b State:
  = @shipping_detail.state
%p
  %b Zip:
  = @shipping_detail.zip
%p
  %b Country:
  = @shipping_detail.country
%p
  %b User:
  = @shipping_detail.user_id

= link_to 'Edit', edit_shipping_detail_path(@shipping_detail)
\|
= link_to 'Back', shipping_details_path